# Generated by Django 2.2.6 on 2019-10-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lalo',
            name='Ves',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=1000),
        ),
        migrations.AddField(
            model_name='lalo',
            name='otkuda',
            field=models.TextField(default=13),
        ),
        migrations.AddField(
            model_name='lalo',
            name='text2',
            field=models.TextField(default=12),
        ),
        migrations.AddField(
            model_name='lalo',
            name='text3',
            field=models.TextField(default=11),
        ),
        migrations.AlterField(
            model_name='lalo',
            name='text',
            field=models.TextField(default=10),
        ),
    ]
