# Generated by Django 2.2.6 on 2019-10-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0002_auto_20191023_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lalo',
            name='otkuda',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lalo',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lalo',
            name='text2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lalo',
            name='text3',
            field=models.TextField(),
        ),
    ]
