# Generated by Django 2.2.6 on 2019-10-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0003_auto_20191023_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lalo',
            old_name='text2',
            new_name='kontakt1',
        ),
        migrations.RenameField(
            model_name='lalo',
            old_name='otkuda',
            new_name='kontakt2',
        ),
        migrations.RenameField(
            model_name='lalo',
            old_name='text3',
            new_name='kuda',
        ),
    ]
