# Generated by Django 2.2.6 on 2019-10-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0004_auto_20191023_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lalo',
            old_name='text',
            new_name='otkuda',
        ),
    ]
