# Generated by Django 2.2.6 on 2019-10-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0005_auto_20191023_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lalo',
            name='otkuda',
            field=models.TextField(max_length=200),
        ),
    ]
