# Generated by Django 2.2.6 on 2019-11-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0006_auto_20191028_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lalo',
            options={'ordering': ('-created_date',)},
        ),
    ]
