# Generated by Django 2.2.6 on 2019-12-14 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lallog', '0007_auto_20191113_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marshrut', models.DecimalField(decimal_places=0, default=10, max_digits=1000)),
                ('ves', models.DecimalField(decimal_places=0, default=10, max_digits=1000)),
                ('from_address', models.CharField(max_length=200)),
                ('from_phone', models.CharField(max_length=200)),
                ('from_comment', models.CharField(max_length=200)),
                ('to', models.CharField(max_length=200)),
                ('to_phone', models.CharField(max_length=200)),
                ('to_date', models.CharField(max_length=200)),
                ('to_date_until', models.CharField(max_length=200)),
                ('to_comment', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=0, default=10, max_digits=1000)),
                ('itog', models.DecimalField(decimal_places=0, default=10, max_digits=1000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
