# Generated by Django 2.2.6 on 2019-12-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0008_testorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='marshrut',
            field=models.CharField(max_length=200),
        ),
    ]
