# Generated by Django 2.2.6 on 2019-12-19 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curier', '0004_auto_20191219_1442'),
        ('Lallog', '0009_auto_20191214_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='curier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='choiced_curier', to='curier.Curier'),
        ),
    ]
