# Generated by Django 2.2.6 on 2019-12-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0013_auto_20191219_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='curier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='choiced_curier', to='curier.Curier'),
        ),
    ]
