# Generated by Django 2.2.6 on 2019-12-20 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0015_auto_20191220_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='curier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='choiced_curier', to='curier.Curier', verbose_name='Product|curier'),
        ),
    ]
