# Generated by Django 2.2.6 on 2019-12-20 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0016_auto_20191220_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='status',
            field=models.CharField(default='Ищем курьеров', max_length=200),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='curier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='choiced_curier', to='curier.Curier'),
        ),
    ]
