# Generated by Django 2.2.6 on 2019-12-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0018_auto_20191223_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='curier_money',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1000),
        ),
    ]
