# Generated by Django 2.2.6 on 2020-01-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0019_testorder_curier_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='status',
            field=models.CharField(default='Ожидание', max_length=200),
        ),
    ]
