# Generated by Django 2.2.6 on 2020-03-13 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0021_testorder_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
