# Generated by Django 2.2.6 on 2020-03-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0022_testorder_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
