# Generated by Django 2.2.6 on 2020-03-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0024_auto_20200313_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
