# Generated by Django 2.2.6 on 2020-03-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lallog', '0027_auto_20200313_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='to_date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
