# Generated by Django 2.2.6 on 2019-11-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curier',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curier',
            name='photo',
            field=models.ImageField(blank=True, upload_to='curiers/%y/%m/%d'),
        ),
    ]
