# Generated by Django 2.2.6 on 2019-12-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curier', '0002_auto_20191119_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curier',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
