# Generated by Django 2.2.6 on 2020-02-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curier', '0006_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='balance_before',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1000),
        ),
    ]
