# Generated by Django 2.2.6 on 2020-03-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curier', '0007_changes_balance_before'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curier',
            name='date_of_birth',
        ),
    ]
