# Generated by Django 2.2.6 on 2020-03-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curier', '0008_remove_curier_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='curier',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='curier',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
