# Generated by Django 2.2.6 on 2019-11-19 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='curier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='curier.Curier'),
        ),
    ]
