# Generated by Django 2.2.6 on 2019-11-19 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191119_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='curier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='curier.Curier'),
        ),
    ]
